"""
Export & Report Generation API endpoints.

Provides export functionality for chat conversations and document analysis.
"""

import logging
import json
from datetime import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

from fastapi import APIRouter, HTTPException, status, Depends
from fastapi.responses import JSONResponse

from app.services.llm import LLMService, get_llm_service
from app.services.vector_store import VectorStore, get_vector_store
from app.middleware.auth import get_user_id

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api", tags=["Export & Reports"])


# ═══════════════════════════════════════════════════════
# EXPORT REPORTS
# ═══════════════════════════════════════════════════════

class ExportMessage(BaseModel):
    role: str  # 'user' or 'ai'
    content: str
    sources: Optional[List[Dict[str, Any]]] = None


class ExportRequest(BaseModel):
    document_id: str
    document_name: str
    messages: List[ExportMessage]
    include_summary: bool = True


class ExportResponse(BaseModel):
    title: str
    generated_at: str
    document_name: str
    content: str  # Markdown formatted report
    message_count: int


@router.post(
    "/export/report",
    response_model=ExportResponse,
    summary="Generate Exportable Report",
    description="Generate a markdown report from a chat conversation with a document."
)
async def export_report(
    request: ExportRequest,
    user_id: str = Depends(get_user_id),
    llm_service: LLMService = Depends(get_llm_service),
    vector_store: VectorStore = Depends(get_vector_store)
):
    """Generate an exportable report from conversation history."""
    try:
        now = datetime.now()
        
        # Build markdown report
        report_lines = [
            f"# Analysis Report: {request.document_name}",
            f"",
            f"**Generated:** {now.strftime('%B %d, %Y at %I:%M %p')}",
            f"**Document:** {request.document_name}",
            f"**Questions Asked:** {len([m for m in request.messages if m.role == 'user'])}",
            f"",
            f"---",
            f"",
        ]

        # If summary requested, generate one
        if request.include_summary and len(request.messages) > 0:
            try:
                conversation_text = "\n".join([
                    f"{'Q' if m.role == 'user' else 'A'}: {m.content}" 
                    for m in request.messages
                ])
                
                summary_messages = [
                    {"role": "system", "content": "You are a financial report writer. Summarize the following Q&A conversation into a brief executive summary. Be concise."},
                    {"role": "user", "content": f"Summarize this conversation:\n\n{conversation_text[:3000]}"}
                ]
                
                summary_response = llm_service._call_openai(
                    messages=summary_messages,
                    temperature=0.3,
                    max_tokens=300
                )
                
                report_lines.extend([
                    "## Executive Summary",
                    "",
                    summary_response["content"],
                    "",
                    "---",
                    "",
                ])
            except Exception as e:
                logger.warning(f"Could not generate summary: {e}")

        # Add Q&A section
        report_lines.extend([
            "## Questions & Answers",
            "",
        ])

        q_num = 0
        for msg in request.messages:
            if msg.role == 'user':
                q_num += 1
                report_lines.extend([
                    f"### Question {q_num}",
                    f"",
                    f"> {msg.content}",
                    f"",
                ])
            else:
                report_lines.extend([
                    f"**Answer:**",
                    f"",
                    msg.content,
                    f"",
                ])
                
                if msg.sources:
                    report_lines.append("**Sources:**")
                    report_lines.append("")
                    for i, src in enumerate(msg.sources, 1):
                        page = src.get("page_number", "?")
                        chunk_type = src.get("chunk_type", "text")
                        report_lines.append(f"- Source {i}: Page {page} ({chunk_type})")
                    report_lines.append("")
                
                report_lines.append("---")
                report_lines.append("")

        # Footer
        report_lines.extend([
            "",
            f"*Report generated by FinRAG on {now.strftime('%Y-%m-%d')}*",
        ])

        content = "\n".join(report_lines)

        return ExportResponse(
            title=f"Analysis Report: {request.document_name}",
            generated_at=now.isoformat(),
            document_name=request.document_name,
            content=content,
            message_count=len(request.messages)
        )

    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": str(e), "error_code": "EXPORT_ERROR"}
        )


# ═══════════════════════════════════════════════════════
# DOCUMENT TAGS
# ═══════════════════════════════════════════════════════

# In-memory tag storage (would be database in production)
_tags_store: Dict[str, Dict[str, List[str]]] = {}  # user_id -> doc_id -> [tags]


class TagRequest(BaseModel):
    document_id: str
    tags: List[str] = Field(..., max_length=20)


class TagResponse(BaseModel):
    document_id: str
    tags: List[str]


@router.post(
    "/documents/{document_id}/tags",
    response_model=TagResponse,
    summary="Set Document Tags",
    description="Add or update tags for a document."
)
async def set_tags(
    document_id: str,
    request: TagRequest,
    user_id: str = Depends(get_user_id)
):
    """Set tags for a document."""
    if user_id not in _tags_store:
        _tags_store[user_id] = {}
    
    # Clean and deduplicate tags
    clean_tags = list(set([t.strip().lower() for t in request.tags if t.strip()]))[:10]
    _tags_store[user_id][document_id] = clean_tags
    
    return TagResponse(document_id=document_id, tags=clean_tags)


@router.get(
    "/documents/{document_id}/tags",
    response_model=TagResponse,
    summary="Get Document Tags",
    description="Get tags for a document."
)
async def get_tags(
    document_id: str,
    user_id: str = Depends(get_user_id)
):
    """Get tags for a document."""
    tags = _tags_store.get(user_id, {}).get(document_id, [])
    return TagResponse(document_id=document_id, tags=tags)


@router.get(
    "/tags",
    summary="Get All Tags",
    description="Get all unique tags used by the user."
)
async def get_all_tags(
    user_id: str = Depends(get_user_id)
):
    """Get all unique tags across all documents."""
    user_tags = _tags_store.get(user_id, {})
    all_tags = set()
    for tags in user_tags.values():
        all_tags.update(tags)
    return {"tags": sorted(list(all_tags))}


@router.delete(
    "/documents/{document_id}/tags/{tag}",
    summary="Remove Tag",
    description="Remove a specific tag from a document."
)
async def remove_tag(
    document_id: str,
    tag: str,
    user_id: str = Depends(get_user_id)
):
    """Remove a tag from a document."""
    tags = _tags_store.get(user_id, {}).get(document_id, [])
    clean_tag = tag.strip().lower()
    if clean_tag in tags:
        tags.remove(clean_tag)
    return {"document_id": document_id, "tags": tags}
